export default {
  index: { title: "Hasiera", type: "page" },
  project: { title: "Proiektuaren ikuspegi orokorra" },
  monorepo: { title: "Monorepoaren egitura" },
  setup: { title: "Tokiko konfigurazioa" },
  environment: { title: "Ingurune-aldagaiak" },
  backend: { title: "Backend" },
  frontend: { title: "Frontend" },
  architecture: { title: "Arkitektura" },
  api: { title: "API erreferentzia" },
  security: { title: "Autentikazioa eta segurtasuna" },
  domain: { title: "Domeinu-eredua" },
  database: { title: "Datu-basea" },
  deployment: { title: "Hedapena" },
  troubleshooting: { title: "Arazoak konpontzea" },
  contributing: { title: "Nola lagundu" },
  "ai-workflow": { title: "AI dokumentazio fluxua" },
  audit: { title: "Dokumentazio ikuskaritza" },
};
