export default {
  index: { title: "Home", type: "page" },
  project: { title: "Project Overview" },
  monorepo: { title: "Monorepo Structure" },
  setup: { title: "Local Setup" },
  environment: { title: "Environment Variables" },
  backend: { title: "Backend" },
  frontend: { title: "Frontend" },
  architecture: { title: "Architecture" },
  api: { title: "API Reference" },
  security: { title: "Auth & Security" },
  domain: { title: "Domain Model" },
  database: { title: "Database" },
  deployment: { title: "Deployment" },
  troubleshooting: { title: "Troubleshooting" },
  contributing: { title: "Contributing" },
  "ai-workflow": { title: "AI Documentation Workflow" },
  audit: { title: "Docs Audit" },
};
